"""Tables, macros, figures and captions for task A2, generated from the result dict.

Called by a2_physgp.py as write_all(R, BOOT_PARAMS, FULL_FIT). Nothing here computes a
new statistic except the law marginals drawn in fig_phys_law, which are evaluated
from the saved full-grid and bootstrap parameters and stored back into R.
"""

import os
import re

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import seaborn as sns  # noqa: E402

import a2_common as A  # noqa: E402

TAB = os.path.join(A.REV, "results", "tables")
FIG = os.path.join(A.REV, "figures")
MACROS = os.path.join(A.REV, "results", "numbers_a2.tex")
CAPTIONS = os.path.join(FIG, "captions_a2.md")

cBlue, cTeal, cAmber, cRed, cGrey = (
    "#3B6FB6",
    "#2A9D8F",
    "#E08D2F",
    "#C8553D",
    "#6C757D",
)
MODEL_COLOR = {"gp": cBlue, "physgp": cAmber}
MODEL_LABEL = {"gp": "plain GP", "physgp": "PhysGP"}
MODEL_MACRO = {"gp": "GP", "physgp": "PhysGP"}
AXIS_MACRO = {"composition": "Comp", "force": "Force", "frequency": "Freq"}
AXIS_TITLE = {
    "composition": "Held-out composition",
    "force": "Held-out force level",
    "frequency": "Held-out frequency level",
}
PARAM_MACRO = {
    "a0": "Azero",
    "a1": "Aone",
    "a2": "Atwo",
    "f0": "Fzero",
    "gamma": "Gamma",
}
PARAM_TEX = {
    "a0": "$a_0$",
    "a1": "$a_1$",
    "a2": "$a_2$",
    "f0": "$f_0$",
    "gamma": r"$\gamma$",
}
PARAM_UNIT = {
    "a0": r"\si{\milli\volt\per\newton}",
    "a1": r"\si{\milli\volt\per\newton}\,/\,wt\%",
    "a2": r"\si{\milli\volt\per\newton}\,/\,(wt\%)$^2$",
    "f0": r"\si{\hertz}",
    "gamma": r"\si{\hertz}",
}
CLIP = -3.0


def style():
    sns.set_theme(style="whitegrid")
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["DejaVu Sans"],
            "font.size": 9,
            "axes.labelsize": 9,
            "axes.titlesize": 9,
            "axes.titleweight": "normal",
            "axes.titlelocation": "left",
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "legend.fontsize": 9,
            "legend.frameon": False,
            "lines.linewidth": 1.2,
            "lines.markersize": 4,
            "axes.linewidth": 0.6,
            "grid.linewidth": 0.4,
            "grid.color": "#DDDDDD",
            "pdf.fonttype": 42,
            "savefig.bbox": "standard",
            "mathtext.fontset": "dejavusans",
        }
    )


# ------------------------------------------------------------------ formatting
def tnum(x, d=2, bold=False):
    """Table cell number with a typeset minus sign."""
    if x is None or not np.isfinite(x):
        return "--"
    s = f"{x:.{d}f}"
    if s.startswith("-"):
        if float(s) == 0:
            s = s[1:]
        else:
            s = "$-$" + s[1:]
    return rf"\textbf{{{s}}}" if bold else s


def sig(x, n=3):
    """Round to n significant digits, return a plain string."""
    if x == 0 or not np.isfinite(x):
        return "0"
    xr = float(f"{x:.{n}g}")  # round first so 9.998 -> 10.0 gets the right number of decimals
    d = max(0, n - 1 - int(np.floor(np.log10(abs(xr)))))
    return f"{xr:.{d}f}"


def tsig(x, n=3):
    s = sig(x, n)
    return "$-$" + s[1:] if s.startswith("-") else s


def mnum(x, d=2):
    """Macro value: plain number, negative sign safe in text and math mode."""
    if x is None:
        return "n/a"
    s = f"{x:.{d}f}"
    if s.startswith("-"):
        s = s[1:] if float(s) == 0 else r"\ensuremath{-}" + s[1:]
    return s


def msig(x, n=3):
    s = sig(x, n)
    return r"\ensuremath{-}" + s[1:] if s.startswith("-") else s


def mcond(x, n=2):
    """Condition number: plain integer below 1000, scientific notation from 1000 up."""
    return str(int(round(x))) if x < 1000 else msci(x, n)


def msci(x, n=2):
    return rf"\num{{{x:.{n - 1}e}}}"


class Macros:
    def __init__(self):
        self.lines = []
        self.names = set()

    def add(self, name, value, comment=None):
        full = "phys" + name
        assert re.fullmatch(r"[A-Za-z]+", full), full
        assert full not in self.names, full
        self.names.add(full)
        c = f"  % {comment}" if comment else ""
        self.lines.append(rf"\newcommand{{\{full}}}{{{value}}}{c}")

    def write(self, path):
        hdr = [
            "% numbers_a2.tex: generated by code/a2_physgp.py (task A2); do not edit by hand.",
            "% Source of every value: results/a2_physgp.json (see its index).",
            "% Law coefficients a0, a1, a2 are in mV/N; f0 and gamma in Hz; MAE in V.",
        ]
        with open(path, "w") as fh:
            fh.write("\n".join(hdr + self.lines) + "\n")
        return len(self.lines)


def write_tab(name, body):
    path = os.path.join(TAB, f"tab_phys_{name}.tex")
    with open(path, "w") as fh:
        fh.write(body.strip() + "\n")
    return path


# ------------------------------------------------------------------ tables
def tab_per_level(R):
    tg = A.TARGETS
    cols = "l r " + " ".join(["rrrr"] * len(tg))
    L = [rf"\begin{{tabular}}{{{cols}}}", r"\toprule"]
    L.append(
        " & & "
        + " & ".join(rf"\multicolumn{{4}}{{c}}{{{A.TARGET_TEX[t]}}}" for t in tg)
        + r" \\"
    )
    L.append(
        " ".join(rf"\cmidrule(lr){{{3 + 4 * i}-{6 + 4 * i}}}" for i in range(len(tg)))
    )
    L.append(
        " & & "
        + " & ".join(
            r"\multicolumn{2}{c}{$R^2$} & \multicolumn{2}{c}{MAE (\si{\volt})}"
            for _ in tg
        )
        + r" \\"
    )
    L.append(
        "Held-out level & $n$ & "
        + " & ".join("GP & PhysGP & GP & PhysGP" for _ in tg)
        + r" \\"
    )
    L.append(r"\midrule")
    for k, ax in enumerate(A.AXES):
        if k:
            L.append(r"\midrule")
        L.append(rf"\multicolumn{{{2 + 4 * len(tg)}}}{{l}}{{{AXIS_TITLE[ax]}}} \\")
        for lvl in A.axis_levels(ax):
            key = A.level_key(ax, lvl)
            n = R["per_level"][tg[0]][ax]["gp"][key]["n"]
            cells = [A.level_tex(ax, lvl), str(n)]
            for t in tg:
                g = R["per_level"][t][ax]["gp"][key]
                p = R["per_level"][t][ax]["physgp"][key]
                cells += [
                    tnum(g["R2"], 2, g["R2"] > p["R2"]),
                    tnum(p["R2"], 2, p["R2"] > g["R2"]),
                    tnum(g["MAE"], 3, g["MAE"] < p["MAE"]),
                    tnum(p["MAE"], 3, p["MAE"] < g["MAE"]),
                ]
            L.append(" & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("per_level", "\n".join(L))


def tab_pooled(R):
    tg = A.TARGETS
    L = [rf"\begin{{tabular}}{{l {' '.join(['rrrr'] * len(tg))}}}", r"\toprule"]
    L.append(
        " & "
        + " & ".join(rf"\multicolumn{{4}}{{c}}{{{A.TARGET_TEX[t]}}}" for t in tg)
        + r" \\"
    )
    L.append(
        " ".join(rf"\cmidrule(lr){{{2 + 4 * i}-{5 + 4 * i}}}" for i in range(len(tg)))
    )
    L.append(
        " & "
        + " & ".join(
            r"\multicolumn{2}{c}{$R^2$} & \multicolumn{2}{c}{MAE (\si{\volt})}"
            for _ in tg
        )
        + r" \\"
    )
    L.append(
        "Validation scheme & "
        + " & ".join("GP & PhysGP & GP & PhysGP" for _ in tg)
        + r" \\"
    )
    L.append(r"\midrule")
    rows = [("Within-grid LOO", "loo", 3)] + [(AXIS_TITLE[ax], ax, 2) for ax in A.AXES]
    for lab, key, d in rows:
        cells = [lab]
        for t in tg:
            g, p = R["pooled"][t][key]["gp"], R["pooled"][t][key]["physgp"]
            cells += [
                tnum(g["R2"], d, g["R2"] > p["R2"]),
                tnum(p["R2"], d, p["R2"] > g["R2"]),
                tnum(g["MAE"], 3, g["MAE"] < p["MAE"]),
                tnum(p["MAE"], 3, p["MAE"] < g["MAE"]),
            ]
        L.append(" & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("pooled", "\n".join(L))


def _mv(name, v):
    return v * 1e3 if name in ("a0", "a1", "a2") else v


def on_bound(pn, v):
    """True when f0 or gamma sits on its fit bound (a0-a2 bounds are never active)."""
    j = A.PNAMES.index(pn)
    if j < 3:
        return False
    return abs(v - A.BOUNDS_5[0][j]) < 1e-6 or abs(v - A.BOUNDS_5[1][j]) < 1e-6


def bmark(pn, v):
    c = tsig(_mv(pn, v))
    return c + r"$^{\dagger}$" if on_bound(pn, v) else c


def bound_notes(R):
    """Group-wise fold extremes of f0 and gamma that sit on a bound, per target."""
    out = []
    for t in A.TARGETS:
        I = R["identifiability"][t]
        for pn in ("f0", "gamma"):
            for q in ("min", "max"):
                v = I["group_folds"]["spread"][pn][q]
                if on_bound(pn, v):
                    ax_lv = []
                    for ax, g in I["group_folds"]["per_axis"].items():
                        for lv, val in zip(g["levels"], g["params"][pn]):
                            if abs(val - v) < 1e-9:
                                ax_lv.append((ax, lv))
                    out.append({"target": t, "param": pn, "stat": q, "value": v, "folds": ax_lv})
    return out


def tab_identifiability(R):
    L = [r"\begin{tabular}{l l r r r c r r r r r r}", r"\toprule"]
    L.append(
        r" & & & \multicolumn{2}{c}{SE} & & \multicolumn{3}{c}{LOO folds ($n=75$)} & \multicolumn{3}{c}{Group-wise folds ($n=13$)} \\"
    )
    L.append(r"\cmidrule(lr){4-5} \cmidrule(lr){7-9} \cmidrule(lr){10-12}")
    L.append(
        r"Parameter & Unit & Estimate & Jacobian & Bootstrap & Bootstrap 95\% CI & min & median & max & min & median & max \\"
    )
    L.append(r"\midrule")
    for k, t in enumerate(A.TARGETS):
        I = R["identifiability"][t]
        if k:
            L.append(r"\midrule")
        L.append(rf"\multicolumn{{12}}{{l}}{{{A.TARGET_TEX[t]}}} \\")
        for pn in A.PNAMES:
            est = _mv(pn, I["full_grid"]["estimate"][pn])
            sej = _mv(pn, I["full_grid"]["se_jacobian"][pn])
            seb = _mv(pn, I["bootstrap"]["se"][pn])
            lo, hi = (_mv(pn, v) for v in I["bootstrap"]["ci95"][pn])
            lf = I["loo_folds"]["spread"][pn]
            gf = I["group_folds"]["spread"][pn]
            L.append(
                " & ".join(
                    [
                        PARAM_TEX[pn],
                        PARAM_UNIT[pn],
                        tsig(est),
                        tsig(sej, 2),
                        tsig(seb, 2),
                        f"[{tsig(lo)}, {tsig(hi)}]",
                    ]
                    + [bmark(pn, lf[q]) for q in ("min", "median", "max")]
                    + [bmark(pn, gf[q]) for q in ("min", "median", "max")]
                )
                + r" \\"
            )
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("identifiability", "\n".join(L))


def tab_corr(R):
    L = [r"\begin{tabular}{l rrrrr}", r"\toprule"]
    L.append(" & " + " & ".join(PARAM_TEX[p] for p in A.PNAMES) + r" \\")
    L.append(r"\midrule")
    for k, t in enumerate(A.TARGETS):
        I = R["identifiability"][t]
        cj, cb = np.array(I["full_grid"]["corr_jacobian"]), np.array(
            I["bootstrap"]["corr"]
        )
        if k:
            L.append(r"\midrule")
        L.append(rf"\multicolumn{{6}}{{l}}{{{A.TARGET_TEX[t]}}} \\")
        for i, pi in enumerate(A.PNAMES):
            cells = [PARAM_TEX[pi]]
            for j in range(5):
                if i == j:
                    cells.append("1")
                elif i > j:
                    cells.append(tnum(cj[i, j], 2))
                else:
                    cells.append(tnum(cb[i, j], 2))
            L.append(" & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("corr", "\n".join(L))


ABL = [
    ("gp", "Plain GP"),
    ("gp_linF", "GP, linear-in-force mean"),
    ("law", "Law alone"),
    ("physgp", "PhysGP"),
    ("physgp_offset", "PhysGP with additive offset"),
]


def tab_ablation(R):
    tg = A.TARGETS
    L = [rf"\begin{{tabular}}{{l {' '.join(['rr'] * len(tg))}}}", r"\toprule"]
    L.append(
        " & "
        + " & ".join(rf"\multicolumn{{2}}{{c}}{{{A.TARGET_TEX[t]}}}" for t in tg)
        + r" \\"
    )
    L.append(
        " ".join(rf"\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(tg)))
    )
    L.append(
        "Mean function & "
        + " & ".join(r"$R^2$ & MAE (\si{\volt})" for _ in tg)
        + r" \\"
    )
    L.append(r"\midrule")
    for k, ax in enumerate(A.AXES):
        if k:
            L.append(r"\midrule")
        L.append(
            rf"\multicolumn{{{1 + 2 * len(tg)}}}{{l}}{{{AXIS_TITLE[ax]}, pooled}} \\"
        )
        best = {t: max(R["pooled"][t][ax][m]["R2"] for m, _ in ABL) for t in tg}
        bmae = {t: min(R["pooled"][t][ax][m]["MAE"] for m, _ in ABL) for t in tg}
        for m, lab in ABL:
            cells = [lab]
            for t in tg:
                v = R["pooled"][t][ax][m]
                cells += [
                    tnum(v["R2"], 2, v["R2"] == best[t]),
                    tnum(v["MAE"], 3, v["MAE"] == bmae[t]),
                ]
            L.append(" & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("ablation", "\n".join(L))


def tab_ablation_levels(R):
    L = [r"\begin{tabular}{l rrrrr}", r"\toprule"]
    L.append(
        "Held-out level & "
        + " & ".join(["GP", "GP, lin.\\ $F$", "Law", "PhysGP", "PhysGP + offset"])
        + r" \\"
    )
    L.append(r"\midrule")
    first = True
    for t in A.TARGETS:
        for ax in A.AXES:
            if not first:
                L.append(r"\midrule")
            first = False
            L.append(
                rf"\multicolumn{{6}}{{l}}{{{A.TARGET_TEX[t]}, {AXIS_TITLE[ax].lower()}}} \\"
            )
            for lvl in A.axis_levels(ax):
                key = A.level_key(ax, lvl)
                vals = [R["per_level"][t][ax][m][key]["R2"] for m, _ in ABL]
                b = max(vals)
                L.append(
                    " & ".join(
                        [A.level_tex(ax, lvl)] + [tnum(v, 2, v == b) for v in vals]
                    )
                    + r" \\"
                )
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("ablation_levels", "\n".join(L))


PICK = {"gp": "GP", "physgp": "Phys"}


def tab_selection(R):
    tg = A.TARGETS
    L = [rf"\begin{{tabular}}{{l {' '.join(['lrlr'] * len(tg))}}}", r"\toprule"]
    L.append(
        " & "
        + " & ".join(rf"\multicolumn{{4}}{{c}}{{{A.TARGET_TEX[t]}}}" for t in tg)
        + r" \\"
    )
    L.append(
        " ".join(rf"\cmidrule(lr){{{2 + 4 * i}-{5 + 4 * i}}}" for i in range(len(tg)))
    )
    L.append(
        " & "
        + " & ".join(
            r"\multicolumn{2}{c}{Inner-CV rule} & \multicolumn{2}{c}{Stability rule}"
            for _ in tg
        )
        + r" \\"
    )
    L.append(
        "Outer held-out level & "
        + " & ".join("pick & $R^2$ & pick & $R^2$" for _ in tg)
        + r" \\"
    )
    L.append(r"\midrule")
    for k, ax in enumerate(A.AXES):
        if k:
            L.append(r"\midrule")
        L.append(rf"\multicolumn{{{1 + 4 * len(tg)}}}{{l}}{{{AXIS_TITLE[ax]}}} \\")
        rows = {
            t: {
                r["held_out_level"]: r
                for r in R["selection_rule"][t][ax]["per_outer_fold"]
            }
            for t in tg
        }
        for lvl in A.axis_levels(ax):
            key = A.level_key(ax, lvl)
            cells = [A.level_tex(ax, lvl)]
            for t in tg:
                r = rows[t][key]
                cells += [
                    PICK[r["pick_inner_cv"]],
                    tnum(r["realized_R2_inner_cv"], 2),
                    PICK[r["pick_stability"]],
                    tnum(r["realized_R2_stability"], 2),
                ]
            L.append(" & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("selection", "\n".join(L))


SEL_ROWS = [
    ("inner_cv", "Inner-CV rule"),
    ("stability", "Stability rule"),
    ("always_gp", "Always plain GP"),
    ("always_physgp", "Always PhysGP"),
    ("oracle", "Per-fold oracle"),
]


def tab_selection_summary(R):
    tg = A.TARGETS
    L = [rf"\begin{{tabular}}{{l {' '.join(['crr'] * len(tg))}}}", r"\toprule"]
    L.append(
        " & "
        + " & ".join(rf"\multicolumn{{3}}{{c}}{{{A.TARGET_TEX[t]}}}" for t in tg)
        + r" \\"
    )
    L.append(
        " ".join(rf"\cmidrule(lr){{{2 + 3 * i}-{4 + 3 * i}}}" for i in range(len(tg)))
    )
    L.append(
        "Strategy & "
        + " & ".join(r"PhysGP picks & $R^2$ & MAE (\si{\volt})" for _ in tg)
        + r" \\"
    )
    L.append(r"\midrule")
    for k, ax in enumerate(A.AXES):
        if k:
            L.append(r"\midrule")
        L.append(
            rf"\multicolumn{{{1 + 3 * len(tg)}}}{{l}}{{{AXIS_TITLE[ax]}, pooled over outer folds}} \\"
        )
        for key, lab in SEL_ROWS:
            cells = [lab]
            for t in tg:
                s = R["selection_rule"][t][ax]["summary"]
                nf = s["n_outer_folds"]
                if key in ("inner_cv", "stability"):
                    picks = f"{s[key]['n_pick_physgp']}/{nf}"
                elif key == "always_gp":
                    picks = f"0/{nf}"
                elif key == "always_physgp":
                    picks = f"{nf}/{nf}"
                else:
                    picks = "--"
                cells += [
                    picks,
                    tnum(s[key]["pooled_R2"], 2),
                    tnum(s[key]["pooled_MAE"], 3),
                ]
            L.append(" & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("selection_summary", "\n".join(L))


def tab_equivalence(R):
    E = R["equivalence"]
    RC = E["restart_check"]
    tg = A.TARGETS

    def sci(v):
        return rf"\num{{{v:.1e}}}"

    L = [
        r"\begin{tabular}{l rrr}",
        r"\toprule",
        "Comparison, maximum over 75 LOO folds & " + " & ".join(A.TARGET_TEX[t] for t in tg) + r" \\",
        r"\midrule",
        r"\multicolumn{4}{l}{Absolute difference (\si{\volt})} \\",
    ]
    rows = [
        ("Law mean, five vs six parameters, tolerance $10^{-15}$", "law_mean_max_abs_diff_tight_tol_V"),
        ("Law mean, five vs six parameters, tolerance $10^{-8}$", "law_mean_max_abs_diff_legacy_tol_V"),
        ("PhysGP, five vs six parameters, tolerance $10^{-15}$", "max_abs_diff_physgp5_vs_physgp6_tight_tol_V"),
        ("PhysGP, five vs six parameters, tolerance $10^{-8}$", "max_abs_diff_physgp5_vs_physgp6_legacy_tol_V"),
        ("PhysGP, five at $10^{-15}$ vs six at $10^{-8}$", "max_abs_diff_physgp5_tight_vs_physgp6_legacy_tol_V"),
    ]
    for lab, k in rows:
        L.append(lab + " & " + " & ".join(sci(E[t][k]) for t in tg) + r" \\")
    L.append(
        "PhysGP, five vs six parameters, four optimizer restarts & "
        + " & ".join(sci(RC[t]["max_abs_diff_physgp5_vs_physgp6_restarts4_V"]) for t in tg)
        + r" \\"
    )
    L.append(
        "PhysGP five vs submitted predictions & "
        + sci(E["rms_Voc"]["max_abs_diff_physgp5_tight_vs_legacy_json_V"])
        + r" & -- & -- \\"
    )
    L.append(
        "Legacy code rerun vs submitted predictions & "
        + sci(E["rms_Voc"]["max_abs_diff_physgp6_legacy_tol_rerun_vs_legacy_json_V"])
        + r" & -- & -- \\"
    )
    sp = E["gp_optimizer_sensitivity_rms"]
    L.append(
        rf"Plain GP after a \num{{{sp['perturbation_sd_V']:.1e}}}~\si{{\volt}} target perturbation & "
        + sci(sp["max_abs_change_gp_loo_prediction_V"])
        + r" & -- & -- \\"
    )
    L.append(r"\midrule")
    L.append(r"\multicolumn{4}{l}{LOO $R^2$} \\")
    L.append("PhysGP five, tolerance $10^{-15}$, reported & " + " & ".join(tnum(E[t]["loo_R2_physgp5_tight"], 3) for t in tg) + r" \\")
    L.append("PhysGP six, tolerance $10^{-15}$ & " + " & ".join(tnum(E[t]["loo_R2_physgp6_tight"], 3) for t in tg) + r" \\")
    L.append("PhysGP six, tolerance $10^{-8}$ & " + " & ".join(tnum(E[t]["loo_R2_physgp6_legacy_tol"], 3) for t in tg) + r" \\")
    L.append("PhysGP five, four optimizer restarts & " + " & ".join(tnum(RC[t]["physgp"]["loo_R2_restarts4"], 3) for t in tg) + r" \\")
    L.append("Plain GP, reported & " + " & ".join(tnum(RC[t]["gp"]["loo_R2_restarts0"], 3) for t in tg) + r" \\")
    L.append("Plain GP, four optimizer restarts & " + " & ".join(tnum(RC[t]["gp"]["loo_R2_restarts4"], 3) for t in tg) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("equivalence", "\n".join(L))


def tab_sensitivity(R):
    D = R["sensitivity_excluding_duplicates"]
    tg = A.TARGETS
    L = [rf"\begin{{tabular}}{{l c {' '.join(['rrrr'] * len(tg))}}}", r"\toprule"]
    L.append(" & & " + " & ".join(rf"\multicolumn{{4}}{{c}}{{{A.TARGET_TEX[t]}}}" for t in tg) + r" \\")
    L.append(" ".join(rf"\cmidrule(lr){{{3 + 4 * i}-{6 + 4 * i}}}" for i in range(len(tg))))
    L.append(" & & " + " & ".join(r"\multicolumn{2}{c}{GP} & \multicolumn{2}{c}{PhysGP}" for _ in tg) + r" \\")
    L.append(" ".join(rf"\cmidrule(lr){{{3 + 2 * i}-{4 + 2 * i}}}" for i in range(2 * len(tg))))
    L.append(r"$R^2$ & $n$ & " + " & ".join("75 & 72 & 75 & 72" for _ in tg) + r" \\")
    L.append(r"\midrule")

    def cells(get75, get72, d):
        out = []
        for t in tg:
            for m in ("gp", "physgp"):
                out += [tnum(get75(t, m), d), tnum(get72(t, m), d)]
        return out

    L.append(
        " & ".join(["Within-grid LOO", f"{A.N}/{D['n']}"]
                   + cells(lambda t, m: R["pooled"][t]["loo"][m]["R2"], lambda t, m: D["loo"][t][m]["R2"], 3))
        + r" \\"
    )
    for ax in A.AXES:
        L.append(
            " & ".join([f"{AXIS_TITLE[ax]}, pooled", f"{A.N}/{D['n']}"]
                       + cells(lambda t, m, ax=ax: R["pooled"][t][ax][m]["R2"],
                               lambda t, m, ax=ax: D["pooled"][t][ax][m]["R2"], 2))
            + r" \\"
        )
        if ax == "force":
            for lvl in A.axis_levels("force"):
                k = A.level_key("force", lvl)
                n75 = R["per_level"][tg[0]]["force"]["gp"][k]["n"]
                n72 = D["per_level"][tg[0]]["force"]["gp"][k]["n"]
                L.append(
                    " & ".join([rf"\quad held-out {A.level_tex('force', lvl)}", f"{n75}/{n72}"]
                               + cells(lambda t, m, k=k: R["per_level"][t]["force"][m][k]["R2"],
                                       lambda t, m, k=k: D["per_level"][t]["force"][m][k]["R2"], 2))
                    + r" \\"
                )
    L.append(r"\midrule")
    L.append(rf"\multicolumn{{{2 + 4 * len(tg)}}}{{l}}{{Force-axis ablation, GP columns linear-in-force mean, PhysGP columns law alone}} \\")
    L.append(
        " & ".join(["Held-out force level", f"{A.N}/{D['n']}"]
                   + cells(lambda t, m: R["pooled"][t]["force"]["gp_linF" if m == "gp" else "law"]["R2"],
                           lambda t, m: D["pooled"][t]["force"]["gp_linF" if m == "gp" else "law"]["R2"], 2))
        + r" \\"
    )
    L += [r"\bottomrule", r"\end{tabular}"]
    return write_tab("sensitivity", "\n".join(L))


# ------------------------------------------------------------------ macros
def macros(R):
    M = Macros()
    E = R["equivalence"]["rms_Voc"]
    M.add(
        "EquivLawMeanDiff",
        msci(E["law_mean_max_abs_diff_tight_tol_V"]),
        "V, law mean 5 vs 6 params, tol 1e-15, max over LOO training sets and 75 rows",
    )
    M.add(
        "EquivLawMeanDiffLegacyTol",
        msci(E["law_mean_max_abs_diff_legacy_tol_V"]),
        "V, same at legacy tol",
    )
    M.add(
        "EquivPredDiff",
        msci(E["max_abs_diff_physgp5_vs_physgp6_tight_tol_V"]),
        "V, PhysGP LOO predictions 5 vs 6 params, tol 1e-15",
    )
    M.add(
        "EquivPredDiffLegacyJson",
        msci(E["max_abs_diff_physgp5_tight_vs_legacy_json_V"]),
        "V, 5-param PhysGP vs submitted LOO predictions",
    )
    M.add(
        "EquivLegacyRerunDiff",
        msci(E["max_abs_diff_physgp6_legacy_tol_rerun_vs_legacy_json_V"]),
        "V, legacy code rerun vs its JSON",
    )
    M.add(
        "EquivGpSensitivity",
        msci(
            R["equivalence"]["gp_optimizer_sensitivity_rms"][
                "max_abs_change_gp_loo_prediction_V"
            ]
        ),
        "V, plain GP LOO change under target perturbation",
    )
    for t in A.TARGETS:
        T = A.TARGET_MACRO[t]
        I = R["identifiability"][t]
        fg = I["full_grid"]
        M.add(
            f"JacCondFive{T}",
            mcond(fg["jacobian_condition_5param"]),
            "condition number of the scaled Jacobian, five-parameter law",
        )
        M.add(
            f"JacCondSix{T}",
            mcond(fg["jacobian_condition_6param_legacy"]),
            "condition number, legacy six-parameter law",
        )
        for pn in A.PNAMES:
            P = PARAM_MACRO[pn]
            M.add(
                f"Law{P}{T}",
                msig(_mv(pn, fg["estimate"][pn])),
                "full-grid estimate (a in mV/N, f0 and gamma in Hz)",
            )
            M.add(
                f"Law{P}{T}Se", msig(_mv(pn, fg["se_jacobian"][pn]), 2), "Jacobian SE"
            )
            M.add(
                f"Law{P}{T}BootSe",
                msig(_mv(pn, I["bootstrap"]["se"][pn]), 2),
                "residual-bootstrap SE",
            )
            M.add(
                f"Law{P}{T}CiLo",
                msig(_mv(pn, I["bootstrap"]["ci95"][pn][0])),
                "bootstrap 95% percentile CI lower",
            )
            M.add(
                f"Law{P}{T}CiHi",
                msig(_mv(pn, I["bootstrap"]["ci95"][pn][1])),
                "bootstrap 95% percentile CI upper",
            )
            for src, key in [("Loo", "loo_folds"), ("Group", "group_folds")]:
                M.add(
                    f"Law{P}{T}{src}Min",
                    msig(_mv(pn, I[key]["spread"][pn]["min"])),
                    f"{key} min",
                )
                M.add(
                    f"Law{P}{T}{src}Median",
                    msig(_mv(pn, I[key]["spread"][pn]["median"])),
                    f"{key} median",
                )
                M.add(
                    f"Law{P}{T}{src}Max",
                    msig(_mv(pn, I[key]["spread"][pn]["max"])),
                    f"{key} max",
                )
        M.add(f"LawQ{T}", mnum(fg["Q_f0_over_gamma"], 2), "f0/gamma")
        if fg["c_star_wt_pct_if_a2_neg"] is not None:
            M.add(
                f"LawCstar{T}",
                mnum(fg["c_star_wt_pct_if_a2_neg"], 2),
                "wt%, -a1/(2 a2)",
            )
        M.add(
            f"LawAloneInSample{T}",
            mnum(fg["law_alone_in_sample_R2"], 2),
            "in-sample R2 of the law alone on the full grid",
        )
        cj, cb = np.array(fg["corr_jacobian"]), np.array(I["bootstrap"]["corr"])
        M.add(f"CorrAoneAtwo{T}", mnum(cj[1, 2], 2), "Jacobian correlation a1-a2")
        M.add(f"CorrAoneAtwoBoot{T}", mnum(cb[1, 2], 2), "bootstrap correlation a1-a2")
        M.add(
            f"AtwoNegLoo{T}",
            str(I["loo_folds"]["a2_negative_count"]),
            "LOO folds with a2 < 0 (of 75)",
        )
        M.add(
            f"AtwoNegGroup{T}",
            str(I["group_folds"]["a2_negative_count"]),
            "group-wise folds with a2 < 0 (of 13)",
        )
        M.add(
            f"AtwoNegBoot{T}",
            mnum(100 * I["bootstrap"]["a2_negative_fraction"], 1),
            "% of bootstrap refits with a2 < 0",
        )
        M.add(
            f"BoundGroup{T}",
            str(I["group_folds"]["n_f0_or_gamma_at_bound"]),
            "group-wise folds with f0 or gamma on a bound",
        )
        M.add(
            f"FzeroSpreadFreq{T}Min",
            mnum(I["group_folds"]["per_axis_spread"]["frequency"]["f0"]["min"], 1),
            "Hz, held-out-frequency folds",
        )
        M.add(
            f"FzeroSpreadFreq{T}Max",
            mnum(I["group_folds"]["per_axis_spread"]["frequency"]["f0"]["max"], 1),
            "Hz, held-out-frequency folds",
        )
    E_ = R["equivalence"]
    RC = E_["restart_check"]
    for t in ("Vpp", "Vmax"):
        T = A.TARGET_MACRO[t]
        M.add(f"EquivPredDiff{T}", msci(E_[t]["max_abs_diff_physgp5_vs_physgp6_tight_tol_V"]), "V, PhysGP LOO 5 vs 6 params, tol 1e-15")
        M.add(f"EquivPredDiffMixed{T}", msci(E_[t]["max_abs_diff_physgp5_tight_vs_physgp6_legacy_tol_V"]), "V, 5 at 1e-15 vs 6 at legacy tol")
        M.add(f"EquivLawMeanDiff{T}", msci(E_[t]["law_mean_max_abs_diff_tight_tol_V"]), "V, law means 5 vs 6, tol 1e-15")
        M.add(f"EquivWorstCondition{T}", str(E_[t]["argmax_condition_physgp5_vs_physgp6_tight_tol"]), "condition id (row of targets_design) of the largest 5 vs 6 gap")
    deltas = []
    for t in A.TARGETS:
        T = A.TARGET_MACRO[t]
        rc = RC[t]
        M.add(f"LooRestart{T}", mnum(rc["physgp"]["loo_R2_restarts4"], 3), "PhysGP LOO R2 with 4 optimizer restarts")
        M.add(f"LooRestartDelta{T}", mnum(rc["physgp"]["delta_R2"], 4), "PhysGP LOO R2 change, restarts 4 minus 0")
        M.add(f"LooRestartGp{T}", mnum(rc["gp"]["loo_R2_restarts4"], 3), "plain GP LOO R2 with 4 optimizer restarts")
        M.add(f"LooRestartGpDelta{T}", mnum(rc["gp"]["delta_R2"], 4), "plain GP LOO R2 change, restarts 4 minus 0")
        M.add(f"LooRestartSixDiff{T}", msci(rc["max_abs_diff_physgp5_vs_physgp6_restarts4_V"]), "V, PhysGP 5 vs 6 params with 4 restarts")
        deltas += [abs(rc["physgp"]["delta_R2"]), abs(rc["gp"]["delta_R2"])]
    M.add("LooRestartMaxAbsDelta", mnum(max(deltas), 4), "largest |LOO R2 change| over targets and both models")
    M.add("LooRestartThreshold", f"{RC['threshold_R2']:g}")
    D = R["sensitivity_excluding_duplicates"]
    M.add("DupN", str(D["n"]), "conditions after removing the duplicated recordings")
    M.add("DupExcluded", ", ".join(str(i) for i in D["excluded_condition_ids"][:-1]) + " and " + str(D["excluded_condition_ids"][-1]), "excluded condition ids")
    for t in A.TARGETS:
        T = A.TARGET_MACRO[t]
        for m in ("gp", "physgp"):
            MM = MODEL_MACRO[m]
            M.add(f"DupLoo{T}{MM}", mnum(D["loo"][t][m]["R2"], 3), "n=72 within-grid LOO R2")
            M.add(f"DupLoo{T}{MM}Mae", mnum(D["loo"][t][m]["MAE"], 3), "n=72 LOO MAE, V")
            for ax in A.AXES:
                AX = AXIS_MACRO[ax]
                M.add(f"Dup{AX}{T}{MM}", mnum(D["pooled"][t][ax][m]["R2"], 2), "n=72 pooled group-wise R2")
                M.add(f"Dup{AX}{T}{MM}Mae", mnum(D["pooled"][t][ax][m]["MAE"], 3), "n=72 pooled group-wise MAE, V")
                M.add(f"DupMeanLevel{AX}{T}{MM}", mnum(D["pooled"][t][ax][m]["mean_within_level_R2"], 2), "n=72 mean within-level R2")
                for lvl in A.axis_levels(ax):
                    v = D["per_level"][t][ax][m][A.level_key(ax, lvl)]
                    LM = A.level_macro(ax, lvl)
                    M.add(f"Dup{LM}{T}{MM}", mnum(v["R2"], 2), "n=72 within-level R2")
                    M.add(f"Dup{LM}{T}{MM}Mae", mnum(v["MAE"], 3), "n=72 within-level MAE, V")
        for m, nm in [("law", "Law"), ("gp_linF", "LinF")]:
            M.add(f"DupAblForce{T}{nm}", mnum(D["pooled"][t]["force"][m]["R2"], 2), f"n=72 pooled force-axis R2, {m}")
            for lvl in A.axis_levels("force"):
                v = D["per_level"][t]["force"][m][A.level_key("force", lvl)]
                M.add(f"DupAbl{A.level_macro('force', lvl)}{T}{nm}", mnum(v["R2"], 2), f"n=72 within-level R2, {m}")
    M.add("NBoot", str(R["meta"]["n_bootstrap"]))
    M.add("NLooFolds", "75")
    M.add("NGroupFolds", str(R["identifiability"]["rms_Voc"]["group_folds"]["n"]))
    M.add("StabFzeroSpread", f"{R['meta']['stability_threshold_Hz']:g}", "Hz")
    # LOO and pooled
    for t in A.TARGETS:
        T = A.TARGET_MACRO[t]
        for m in ("gp", "physgp"):
            MM = MODEL_MACRO[m]
            M.add(
                f"Loo{T}{MM}",
                mnum(R["pooled"][t]["loo"][m]["R2"], 3),
                "within-grid LOO R2",
            )
            M.add(
                f"Loo{T}{MM}Mae",
                mnum(R["pooled"][t]["loo"][m]["MAE"], 3),
                "within-grid LOO MAE, V",
            )
            for ax in A.AXES:
                AX = AXIS_MACRO[ax]
                p = R["pooled"][t][ax][m]
                M.add(
                    f"Pooled{AX}{T}{MM}",
                    mnum(p["R2"], 2),
                    "pooled group-wise R2, global denominator",
                )
                M.add(
                    f"Pooled{AX}{T}{MM}Mae",
                    mnum(p["MAE"], 3),
                    "pooled group-wise MAE, V",
                )
                M.add(
                    f"MeanLevel{AX}{T}{MM}",
                    mnum(p["mean_within_level_R2"], 2),
                    "mean of within-level R2 over held-out levels",
                )
                M.add(
                    f"NegLevels{AX}{T}{MM}",
                    str(p["n_levels_R2_negative"]),
                    "held-out levels with within-level R2 < 0",
                )
                for lvl in A.axis_levels(ax):
                    v = R["per_level"][t][ax][m][A.level_key(ax, lvl)]
                    LM = A.level_macro(ax, lvl)
                    M.add(f"{LM}{T}{MM}", mnum(v["R2"], 2), "within-level R2")
                    M.add(f"{LM}{T}{MM}Mae", mnum(v["MAE"], 3), "within-level MAE, V")
                    M.add(
                        f"{LM}{T}{MM}Bias",
                        mnum(v["bias"], 3),
                        "within-level mean(pred - y), V",
                    )
                    M.add(
                        f"{LM}{T}{MM}Corr",
                        mnum(v["pearson_r"], 2),
                        "within-level Pearson r of pred and y",
                    )
        for ax in A.AXES:
            AX = AXIS_MACRO[ax]
            for m, nm in [
                ("law", "Law"),
                ("gp_linF", "LinF"),
                ("physgp_offset", "Offset"),
            ]:
                M.add(
                    f"Abl{AX}{T}{nm}",
                    mnum(R["pooled"][t][ax][m]["R2"], 2),
                    f"pooled R2, ablation {m}",
                )
            S = R["selection_rule"][t][ax]["summary"]
            for key, nm in [("inner_cv", "Cv"), ("stability", "Stab")]:
                M.add(
                    f"Sel{nm}{AX}{T}Picks",
                    str(S[key]["n_pick_physgp"]),
                    f"outer folds where rule {key} picks PhysGP",
                )
                M.add(
                    f"Sel{nm}{AX}{T}Match",
                    str(S[key]["n_match_oracle"]),
                    f"outer folds where rule {key} picks the better model",
                )
                M.add(
                    f"Sel{nm}{AX}{T}Rsq",
                    mnum(S[key]["pooled_R2"], 2),
                    f"pooled R2 of rule {key}",
                )
                M.add(
                    f"Sel{nm}{AX}{T}Mae",
                    mnum(S[key]["pooled_MAE"], 3),
                    f"pooled MAE of rule {key}, V",
                )
            M.add(
                f"SelOracle{AX}{T}Rsq",
                mnum(S["oracle"]["pooled_R2"], 2),
                "pooled R2 of the per-fold oracle",
            )
    for ax in A.AXES:
        M.add(
            f"NFolds{AXIS_MACRO[ax]}",
            str(R["selection_rule"]["rms_Voc"][ax]["summary"]["n_outer_folds"]),
        )
    return M.write(MACROS)


# ------------------------------------------------------------------ figures
def save(fig, name):
    fig.savefig(os.path.join(FIG, f"{name}.pdf"))
    fig.savefig(os.path.join(FIG, f"{name}.png"), dpi=150)
    plt.close(fig)


def level_ticklabel(ax_name, lvl):
    if ax_name == "composition":
        return {
            "PVDF": "PVDF",
            "PVDF+BaTiO3": "BTO",
            "PVDF+BaTiO3+%1CNT": "1%",
            "PVDF+BaTiO3+%2CNT": "2%",
            "PVDF+BaTiO3+%3CNT": "3%",
        }[lvl]
    return f"{int(lvl)}"


def fig_axes(R):
    style()
    fig, axs = plt.subplots(3, 3, figsize=(6.85, 6.4), sharey=True, layout="constrained")
    clipped = []
    w = 0.38
    letters = iter("abcdefghi")
    for i, t in enumerate(A.TARGETS):
        for j, axn in enumerate(A.AXES):
            ax = axs[i, j]
            lv = A.axis_levels(axn)
            x = np.arange(len(lv))
            for k, m in enumerate(("gp", "physgp")):
                vals = np.array(
                    [R["per_level"][t][axn][m][A.level_key(axn, v)]["R2"] for v in lv]
                )
                shown = np.maximum(vals, CLIP)
                xs = x + (k - 0.5) * w
                ax.bar(
                    xs,
                    shown,
                    width=w,
                    color=MODEL_COLOR[m],
                    label=MODEL_LABEL[m],
                    edgecolor="none",
                    zorder=2,
                )
                for xx, v, lvl in zip(xs, vals, lv):
                    if v < CLIP:
                        pass
                        ax.text(
                            xx,
                            CLIP + 0.12,
                            f"{v:.1f}".replace("-", "\u2212"),
                            rotation=90,
                            ha="center",
                            va="bottom",
                            color="white",
                            fontsize=9,
                            zorder=4,
                        )
                        clipped.append(
                            {
                                "target": t,
                                "axis": axn,
                                "level": A.level_key(axn, lvl),
                                "model": m,
                                "R2": float(v),
                            }
                        )
            ax.axhline(0, color="black", lw=0.6, zorder=1)
            ax.set_ylim(CLIP - 0.1, 1.05)
            ax.set_xticks(x)
            ax.set_xticklabels([level_ticklabel(axn, v) for v in lv])
            ax.set_title(
                f"({next(letters)}) {A.TARGET_LABEL[t]}, {axn}",
                fontsize=9,
            )
            if j == 0:
                ax.set_ylabel(r"Within-level $R^2$")
            if i == 2:
                ax.set_xlabel(
                    {
                        "composition": "Held-out composition (CNT wt%)",
                        "force": "Held-out force (N)",
                        "frequency": "Held-out frequency (Hz)",
                    }[axn]
                )
            ax.grid(axis="x", visible=False)
    h, l_ = axs[0, 0].get_legend_handles_labels()
    fig.legend(h, l_, loc="outside upper center", ncol=2)
    save(fig, "fig_phys_axes")
    return clipped


def law_marginals(params_list):
    """Law marginals on the design grid for a list of volt-scale parameter vectors."""
    comps_c = np.array([0.0, 0.0, 1.0, 2.0, 3.0])
    forces = np.array([1.0, 2.0, 3.0])
    freqs = np.array([5.0, 10.0, 15.0, 20.0, 25.0])
    fgrid = np.linspace(4.0, 26.0, 221)
    P = np.atleast_2d(params_list)
    out = {"fgrid": fgrid, "freq": [], "force": [], "comp": []}
    for p in P:
        a0, a1, a2, f0, g = p
        comp_fac = a0 + a1 * comps_c + a2 * comps_c**2  # per composition, V/N
        out["freq"].append(comp_fac.mean() * forces.mean() * A.lorentz(fgrid, f0, g))
        out["force"].append(comp_fac.mean() * forces * A.lorentz(freqs, f0, g).mean())
        out["comp"].append(comp_fac * forces.mean() * A.lorentz(freqs, f0, g).mean())
    return {k: np.array(v) if k != "fgrid" else v for k, v in out.items()}


def fig_law(R, BOOT, FULL):
    style()
    fig, axs = plt.subplots(3, 3, figsize=(6.85, 6.6), layout="constrained")
    letters = iter("abcdefghi")
    store = {}
    comp_x = np.arange(5)
    for i, t in enumerate(A.TARGETS):
        y = A.df[t].values
        mfit = law_marginals(FULL[t])
        mb = law_marginals(BOOT[t])
        store[t] = {}
        # frequency
        ax = axs[i, 0]
        lo, hi = np.percentile(mb["freq"], [2.5, 97.5], axis=0)
        ax.fill_between(
            mfit["fgrid"],
            lo,
            hi,
            color=cAmber,
            alpha=0.3,
            lw=0,
            label="law, bootstrap 95% band",
        )
        ax.plot(
            mfit["fgrid"], mfit["freq"][0], color=cAmber, label="law, full-grid fit"
        )
        ax.scatter(
            A.FRQ,
            y,
            s=6,
            color=cGrey,
            alpha=0.5,
            lw=0,
            label="single condition",
            zorder=2,
        )
        fm = [y[A.FRQ == v].mean() for v in [5, 10, 15, 20, 25]]
        ax.plot(
            [5, 10, 15, 20, 25],
            fm,
            "o",
            color="black",
            ms=4,
            label="measured mean",
            zorder=3,
        )
        ax.set_title(f"({next(letters)}) {A.TARGET_LABEL[t]} vs frequency", fontsize=9)
        ax.set_xlabel("Frequency (Hz)" if i == 2 else "")
        ax.set_ylabel(f"{A.TARGET_LABEL[t]} (V)")
        store[t]["freq"] = {
            "measured_mean": fm,
            "law_at_levels": [
                float(np.interp(v, mfit["fgrid"], mfit["freq"][0]))
                for v in [5, 10, 15, 20, 25]
            ],
        }
        # force
        ax = axs[i, 1]
        lo, hi = np.percentile(mb["force"], [2.5, 97.5], axis=0)
        ax.fill_between([1, 2, 3], lo, hi, color=cAmber, alpha=0.3, lw=0)
        ax.plot([1, 2, 3], mfit["force"][0], color=cAmber)
        ax.scatter(A.FRC, y, s=6, color=cGrey, alpha=0.5, lw=0, zorder=2)
        Fm = [y[A.FRC == v].mean() for v in [1, 2, 3]]
        ax.plot([1, 2, 3], Fm, "o", color="black", ms=4, zorder=3)
        ax.set_xticks([1, 2, 3])
        ax.set_title(f"({next(letters)}) {A.TARGET_LABEL[t]} vs force", fontsize=9)
        ax.set_xlabel("Nominal force (N)" if i == 2 else "")
        store[t]["force"] = {
            "measured_mean": Fm,
            "law": mfit["force"][0].tolist(),
            "band": [lo.tolist(), hi.tolist()],
        }
        # composition
        ax = axs[i, 2]
        lo, hi = np.percentile(mb["comp"], [2.5, 97.5], axis=0)
        cm = mfit["comp"][0]
        ax.errorbar(
            comp_x + 0.12,
            cm,
            yerr=[cm - lo, hi - cm],
            fmt="s",
            color=cAmber,
            ms=4,
            capsize=2,
            lw=1.0,
            zorder=3,
        )
        ci = np.array([A.COMP_ORDER.index(c) for c in A.COMP])
        ax.scatter(ci - 0.12, y, s=6, color=cGrey, alpha=0.5, lw=0, zorder=2)
        Cm = [y[A.COMP == c].mean() for c in A.COMP_ORDER]
        ax.plot(comp_x - 0.12, Cm, "o", color="black", ms=4, zorder=3)
        ax.set_xticks(comp_x)
        ax.set_xticklabels([level_ticklabel("composition", c) for c in A.COMP_ORDER])
        ax.set_title(
            f"({next(letters)}) {A.TARGET_LABEL[t]} vs composition", fontsize=9
        )
        ax.set_xlabel("Composition (CNT wt%)" if i == 2 else "")
        store[t]["comp"] = {
            "measured_mean": Cm,
            "law": cm.tolist(),
            "band": [lo.tolist(), hi.tolist()],
        }
        for a in axs[i]:
            a.set_ylim(bottom=0)
    h, l_ = axs[0, 0].get_legend_handles_labels()
    fig.legend(h, l_, loc="outside upper center", ncol=4)
    save(fig, "fig_phys_law")
    return store


# ------------------------------------------------------------------ captions
def _level_words(ax, lv):
    if ax == "frequency":
        return f"the fold that holds out {lv}~Hz"
    if ax == "force":
        return f"the fold that holds out {lv}~N"
    return f"the fold that holds out {A.COMP_TEX[lv]}"


def captions(R, clipped):
    nb = R["meta"]["n_bootstrap"]
    E_ = R["equivalence"]
    RC = E_["restart_check"]
    # bound note for the identifiability table
    notes = bound_notes(R)
    R["identifiability_bound_notes"] = notes
    groups = {}
    for n_ in notes:
        for ax, lv in n_["folds"]:
            key = (n_["param"], n_["stat"], round(n_["value"], 6), ax, lv)
            groups.setdefault(key, []).append(A.TARGET_TEX[n_["target"]])
    pword = {"f0": "resonance center $f_0$", "gamma": "resonance width $\\gamma$"}
    bsent = []
    for (pn, q, v, ax, lv), tl in groups.items():
        tls = tl[0] if len(tl) == 1 else ", ".join(tl[:-1]) + " and " + tl[-1]
        side = "upper" if q == "max" else "lower"
        bsent.append(f"For {tls} the {pword[pn]} sits on its {side} fit bound of {v:g}~Hz in {_level_words(ax, lv)}.")
    bound_txt = (
        "A dagger marks a group-wise fold extreme that sits on a fit bound. " + " ".join(bsent)
        if bsent
        else "No group-wise fold extreme sits on a fit bound."
    )
    r2law = {t: R["identifiability"][t]["full_grid"]["law_alone_in_sample_R2"] for t in A.TARGETS}
    boot_txt = (
        "The Jacobian and bootstrap standard errors treat the full-grid residuals as exchangeable, whereas the "
        "law misfit is structured, with an in-sample $R^2$ of the law alone of "
        f"{r2law['rms_Voc']:.2f} for \\RMS, {r2law['Vpp']:.2f} for \\Vpp and {r2law['Vmax']:.2f} for \\Vmax. "
        "Both standard errors and the bootstrap interval are therefore likely optimistic, and the spread over "
        "the group-wise folds is the more conservative reading of parameter uncertainty."
    )
    force_txt = (
        "On the force axis only two force levels remain after the outer split, so every inner model is trained "
        "on a single force level. The plain GP then sees no force variation, while the law imposes "
        "proportionality to force, so the inner-CV rule structurally favors PhysGP on this axis."
    )
    worst = {t: E_[t]["argmax_condition_physgp5_vs_physgp6_tight_tol"] for t in A.TARGETS}
    mixed = {t: E_[t]["argmax_condition_physgp5_tight_vs_physgp6_legacy_tol"] for t in A.TARGETS}
    deltas = {t: RC[t]["physgp"]["delta_R2"] for t in A.TARGETS}
    thr = RC["threshold_R2"]
    moved = [t for t in A.TARGETS if abs(deltas[t]) > thr]
    if moved:
        mv = ", ".join(f"{A.TARGET_TEX[t]} by {deltas[t]:+.4f}" for t in moved)
        restart_txt = (
            f"With four additional optimizer starts the PhysGP LOO $R^2$ moves by more than {thr:g} for {mv}, "
            "so the reported single-start values carry optimizer uncertainty of that size."
        )
    else:
        md = max(abs(v) for v in deltas.values())
        restart_txt = (
            f"With four additional optimizer starts the PhysGP LOO $R^2$ changes by at most {md:.4f} over the "
            f"three targets, which is below the {thr:g} tolerance, so the reported single-start values stand within that tolerance."
        )
    gp_moved = [t for t in A.TARGETS if RC[t]["gp"]["moves_more_than_threshold"]]
    if gp_moved:
        restart_txt += " The plain GP LOO $R^2$ moves by more than the tolerance for " + ", ".join(
            f"{A.TARGET_TEX[t]}, by {RC[t]['gp']['delta_R2']:+.4f}" for t in gp_moved
        ) + "."
    persist = [t for t in A.TARGETS if RC[t]["max_abs_diff_physgp5_vs_physgp6_restarts4_V"] > 1e-3]
    if persist:
        parts = [f"{RC[t]['max_abs_diff_physgp5_vs_physgp6_restarts4_V']:.3f}~V for {A.TARGET_TEX[t]}" for t in persist]
        restart_txt += " The restarts do not remove the gap between the two forms, which stays at " + (
            parts[0] if len(parts) == 1 else ", ".join(parts[:-1]) + " and " + parts[-1]
        ) + ", so the marginal likelihood has several nearly equivalent optima for these targets."
    D = R["sensitivity_excluding_duplicates"]
    ids = D["excluded_condition_ids"]
    dup_txt = (
        "Within-grid leave-one-out and group-wise $R^2$ of the plain GP and PhysGP on the published 75 conditions "
        f"and after removing conditions {ids[0]}, {ids[1]} and {ids[2]}, which leaves {D['n']} conditions. Conditions "
        f"{ids[0]} and {ids[1]} are exact scalar multiples of the 1~N recordings of the 2 wt\\% CNT device at the same "
        f"frequencies, and condition {ids[2]} is a near copy of a pristine PVDF recording. Every model, law fit and "
        "fold is recomputed on the reduced grid, and pooled values use the reduced grid as reference. The held-out "
        "force rows give within-level $R^2$, and $n$ gives the conditions per row at 75 and 72. In the ablation row "
        "the GP columns hold the GP with a linear-in-force mean and the PhysGP columns hold the law alone. "
        "The two exact copies lie on the force axis of the best device and follow a force proportionality by "
        "construction, so they mechanically favor a linear-in-force mean at those cells. The force-axis values at "
        f"{D['n']} conditions are therefore the more conservative figure for the force-axis rescue."
    )
    eq_txt = (
        "Maximum absolute difference over the 75 leave-one-out folds between the five-parameter and the legacy "
        "six-parameter forms of the physical mean, with the resulting LOO $R^2$. The law means of the two forms agree "
        "to about $10^{-8}$~V at tolerance $10^{-15}$ for all three targets. The PhysGP predictions still differ in "
        f"single folds, by up to {E_['Vpp']['max_abs_diff_physgp5_vs_physgp6_tight_tol_V']:.2f}~V for \\Vpp at condition "
        f"{worst['Vpp']} with both forms at tolerance $10^{{-15}}$ and by "
        f"{E_['Vmax']['max_abs_diff_physgp5_tight_vs_physgp6_legacy_tol_V']:.3f}~V for \\Vmax at condition {mixed['Vmax']} "
        "between the five-parameter form at tolerance $10^{-15}$ and the six-parameter form at the legacy tolerance. "
        "These gaps come from the GP hyperparameter optimizer, which starts once and reaches different local optima "
        "of the marginal likelihood for residual vectors that agree to about $10^{-8}$~V. " + restart_txt
    )
    ncl = len(clipped)
    txt = f"""# Captions generated by task A2 (generated by code/a2_report.py)

Numbers in these captions are the generated values at the time of the run. Writers should replace any number that the section quotes with the matching macro from numbers_a2.tex.

## fig_phys_axes

Within-level coefficient of determination of the plain Gaussian process and of PhysGP when one level of one design factor is withheld from training. Rows show the three voltage targets \\RMS, \\Vpp and \\Vmax, and columns show the held-out composition, the held-out force level and the held-out frequency level. Each bar is computed only from the out-of-fold predictions of the conditions in one held-out level, which are 15 conditions for a composition or frequency level and 25 conditions for a force level, and its reference mean is the mean of that level. Nothing is averaged across levels, targets or repeated runs. The physical mean is refitted on the training rows of every fold. Bars below $R^2 = -3$ are clipped at $-3$ and labeled with their actual value, which applies to {ncl} bars. On the composition axis PVDF denotes pristine PVDF, BTO denotes PVDF/BaTiO$_3$, and 1%, 2% and 3% denote PVDF/BaTiO$_3$ with that MWCNT loading in wt%.

## fig_phys_law

Five-parameter voltage law fitted once to all 75 conditions, compared with the measured marginal means of each target. Columns show the dependence on excitation frequency, nominal force and composition. In every panel a grey dot is one condition, a black dot is the measured mean over all conditions that share the abscissa value, and the amber curve or square is the law evaluated on the same 75 design points and averaged over the same conditions. The frequency curve is evaluated on a continuous frequency axis and averaged over the 15 composition and force combinations. The force line averages over the 25 composition and frequency combinations, and the composition markers average over the 15 force and frequency combinations. The shaded band and the error bars are the 2.5th to 97.5th percentiles of the same averaged law over {nb} residual-bootstrap refits of the five parameters. The band inherits the exchangeable-residual assumption of that bootstrap and is likely too narrow for the structured law misfit. The law assigns the same value to pristine PVDF and PVDF/BaTiO$_3$ because both carry zero CNT loading. Composition labels follow Fig. fig_phys_axes.

## Table bodies

tab_phys_per_level. Within-level $R^2$ and mean absolute error of the plain GP and PhysGP for every held-out level of the three design factors and the three voltage targets. Each value uses only the out-of-fold predictions of the held-out level, with $n$ conditions per level. Bold marks the better model of each pair.

tab_phys_pooled. Within-grid leave-one-out and pooled group-wise $R^2$ and mean absolute error for the plain GP and PhysGP. Pooled group-wise values are computed from all 75 out-of-fold predictions of one validation scheme with the global mean as reference.

tab_phys_identifiability. Estimates of the five law parameters on the full grid with standard errors from the Jacobian and from {nb} residual-bootstrap refits, the bootstrap 95% percentile interval, and the minimum, median and maximum of each parameter over the 75 leave-one-out training sets and the 13 group-wise training sets. The coefficients $a_0$, $a_1$ and $a_2$ are given in millivolts per newton. {bound_txt} {boot_txt}

tab_phys_corr. Correlation of the law parameter estimates on the full grid. Entries below the diagonal come from the Jacobian covariance and entries above the diagonal from the residual bootstrap.

tab_phys_ablation. Pooled group-wise $R^2$ and mean absolute error for five mean functions under each held-out axis. The law alone uses no Gaussian process. The linear-in-force mean is refitted by least squares on the training rows. The offset variant adds a free constant to the law.

tab_phys_ablation_levels. Within-level $R^2$ of the five mean functions for every held-out level and target.

tab_phys_selection. Model picked by each selection rule and the realized within-level $R^2$ on the outer held-out level. The inner-CV rule runs leave-one-level-out along the same axis on the training rows of the outer fold and picks the model with the higher inner pooled $R^2$. The stability rule picks PhysGP only when the inner-fold resonance centers span less than {R['meta']['stability_threshold_Hz']:g}~Hz and the sign of $a_2$ is the same in every inner fold. {force_txt}

tab_phys_selection_summary. Pooled $R^2$ and mean absolute error of the out-of-fold predictions produced by each selection strategy, with the number of outer folds in which the strategy uses PhysGP. The per-fold oracle picks the better model after seeing the outer held-out level and is an upper reference, not a usable rule.

tab_phys_equivalence. {eq_txt}

tab_phys_sensitivity. {dup_txt}
"""
    with open(CAPTIONS, "w") as fh:
        fh.write(txt)


# ------------------------------------------------------------------ driver
def write_all(R, BOOT, FULL):
    os.makedirs(TAB, exist_ok=True)
    os.makedirs(FIG, exist_ok=True)
    tabs = {
        "tab_phys_per_level.tex": (
            tab_per_level(R),
            ["per_level.<target>.<axis>.{gp,physgp}.<level>.{n,R2,MAE}"],
        ),
        "tab_phys_pooled.tex": (
            tab_pooled(R),
            ["pooled.<target>.{loo,composition,force,frequency}.{gp,physgp}.{R2,MAE}"],
        ),
        "tab_phys_identifiability.tex": (
            tab_identifiability(R),
            [
                "identifiability.<target>.full_grid.{estimate,se_jacobian}",
                "identifiability.<target>.bootstrap.{se,ci95}",
                "identifiability.<target>.{loo_folds,group_folds}.spread",
            ],
        ),
        "tab_phys_corr.tex": (
            tab_corr(R),
            [
                "identifiability.<target>.full_grid.corr_jacobian",
                "identifiability.<target>.bootstrap.corr",
            ],
        ),
        "tab_phys_ablation.tex": (
            tab_ablation(R),
            ["pooled.<target>.<axis>.{gp,gp_linF,law,physgp,physgp_offset}.{R2,MAE}"],
        ),
        "tab_phys_ablation_levels.tex": (
            tab_ablation_levels(R),
            [
                "per_level.<target>.<axis>.{gp,gp_linF,law,physgp,physgp_offset}.<level>.R2"
            ],
        ),
        "tab_phys_selection.tex": (
            tab_selection(R),
            [
                "selection_rule.<target>.<axis>.per_outer_fold[].{pick_inner_cv,realized_R2_inner_cv,pick_stability,realized_R2_stability}"
            ],
        ),
        "tab_phys_selection_summary.tex": (
            tab_selection_summary(R),
            ["selection_rule.<target>.<axis>.summary"],
        ),
        "tab_phys_sensitivity.tex": (
            tab_sensitivity(R),
            [
                "sensitivity_excluding_duplicates.{loo,pooled,per_level}",
                "pooled.<target>.{loo,composition,force,frequency}.{gp,physgp}.R2",
                "per_level.<target>.force.{gp,physgp}.<level>.R2",
                "pooled.<target>.force.{law,gp_linF}.R2",
            ],
        ),
        "tab_phys_equivalence.tex": (
            tab_equivalence(R),
            ["equivalence.rms_Voc", "equivalence.gp_optimizer_sensitivity_rms"],
        ),
    }
    clipped = fig_axes(R)
    R["figure_data"] = {"fig_phys_axes_clipped_bars": clipped, "clip_value": CLIP}
    R["figure_data"]["fig_phys_law_marginals"] = fig_law(R, BOOT, FULL)
    captions(R, clipped)
    n_macros = macros(R)
    idx = {f"results/tables/{k}": v[1] for k, v in tabs.items()}
    idx["figures/fig_phys_axes.pdf"] = [
        "per_level.<target>.<axis>.{gp,physgp}.<level>.R2",
        "figure_data.fig_phys_axes_clipped_bars",
    ]
    idx["figures/fig_phys_law.pdf"] = [
        "identifiability.<target>.full_grid.estimate",
        "identifiability.<target>.bootstrap.resamples_volt_scale",
        "figure_data.fig_phys_law_marginals",
    ]
    idx["results/numbers_a2.tex"] = [
        "equivalence",
        "identifiability",
        "pooled",
        "per_level",
        "selection_rule",
        "meta.n_bootstrap",
        "meta.stability_threshold_Hz",
        "sensitivity_excluding_duplicates",
    ]
    idx["results/a2_predictions.csv"] = [
        "out-of-fold predictions of gp, physgp, law, gp_linF, physgp_offset, rule_inner_cv, rule_stability; split schemes ending in _excl_dup are the n = 72 sensitivity runs"
    ]
    idx["figures/captions_a2.md"] = [
        "meta.n_bootstrap",
        "figure_data.fig_phys_axes_clipped_bars",
    ]
    R["index"] = idx
    R["meta"]["n_macros"] = n_macros
    return n_macros
